#!/bin/bash

set -e

SSH_DIR="$HOME/.ssh"
DOTFILES_DIR="$PWD"

if ! [ -x "$(command -v ansible)" ]; then
    sudo pacman -S ansible --noconfirm
fi

if ! [[ -f "$SSH_DIR/id_rsa" ]]; then
    mkdir -p "$SSH_DIR" # -p: create parent directories as needed

    chmod 700 "$SSH_DIR" # 700: read, write, exec for user; none for groups and others

    ssh-keygen -b 4096 -t rsa -f "$SSH_DIR/id_rsa" -N "" -C "$USER@$HOSTNAME"

    cat "$SSH_DIR/id_rsa.pub" >> "$SSH_DIR/authorized_keys"

    chmod 600 "$SSH_DIR/authorized_keys"
fi

if [[ -f "$DOTFILES_DIR/requirements.yml" ]]; then
    cd "$DOTFILES_DIR"

    ansible-galaxy install -r requirements.yml
fi

cd "$DOTFILES_DIR"

ansible-playbook --diff "$DOTFILES_DIR/main.yml"


